CREATE USER loguser WITH PASSWORD 'minilp';
ALTER ROLE loguser CREATEDB; 
CREATE DATABASE logdb OWNER loguser;
-- CREATE TABLE IF NOT EXISTS logtable (
--     ID SERIAL PRIMARY KEY,
--     IP VARCHAR(20),
--     LOG VARCHAR(1000),
--     TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );